---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: network
  labels:
    io.portainer.kubernetes.application.stack: nginx
    app.kubernetes.io/name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx-http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: nginx-https
  selector:
    app.kubernetes.io/name: nginx

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: network
  labels:
    io.portainer.kubernetes.application.stack: nginx
    app.kubernetes.io/name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      volumes:
        - name: data-etc
          persistentVolumeClaim:
            claimName: nginx-etc
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          volumeMounts:
            - name: data-etc
              mountPath: "/etc/nginx"
          ports:
            - name: nginx-http
              containerPort: 80
              protocol: TCP
            - name: nginx-https
              containerPort: 443
              protocol: TCP
